### ISSUE TITLE
DC-Mocks cannot decrypt message created by lib-vau-csharp, exception occurs

### ISSUE THREAD

**Issue by CEiderEVIDENT** [gematik/lib-vau-csharp#5] opened 2024-10-08 05:28 UTC
After establishing a connection to the VAU-server within latest docker-image dc-mocks we try to send a request to /VAU-Status.
Building the required inner request on using this c# implementation results in an exception:

```java
2024-10-08 07:22:32 05:22:32.594 VPS TRACE EncryptedVauMessage: trying to decrypt:
2024-10-08 07:22:32       Complete message     : 0200010000000000000000a747e577ccfaf6ded00a4678f702d70bf47434ee26c7b4cb423081b420f272460148584f000000000000000083bcf012777196d5902fe34f02703580133e962f97e520df809402c4d063d1374b2e891ace023fff9de96d72cbc517f48842e0e06838785c96ea30d9ead871c250f5829aa06cd418fce8928a371c7ae7d4c720162e27592f8aa6c49fe1c1e62cb6df0f740f
2024-10-08 07:22:32       Message size (Bytes) : 156
2024-10-08 07:22:32       Complete header      : 0200010000000000000000a747e577ccfaf6ded00a4678f702d70bf47434ee26c7b4cb423081b420f27246
2024-10-08 07:22:32       Key to decrypt (K2_c2s_app_data): f141033ea97ac7c6d8d432dc5c590134393d18a98d1c3113c973d0d194382c0a
2024-10-08 07:22:32       -------------------------------
2024-10-08 07:22:32       Version  (1 Byte): 02
2024-10-08 07:22:32       PU       (1 Byte): 00
2024-10-08 07:22:32       Request  (1 Byte): 01
2024-10-08 07:22:32       Counter  (8 Byte): 0000000000000000
2024-10-08 07:22:32       KeyId   (32 Byte): a747e577ccfaf6ded00a4678f702d70bf47434ee26c7b4cb423081b420f27246
2024-10-08 07:22:32       IV      (12 Byte): 0148584f0000000000000000
2024-10-08 07:22:32       CT + GMAC        : 83bcf012777196d5902fe34f02703580133e962f97e520df809402c4d063d1374b2e891ace023fff9de96d72cbc517f48842e0e06838785c96ea30d9ead871c250f5829aa06cd418fce8928a371c7ae7d4c720162e27592f8aa6c49fe1c1e62cb6df0f740f
2024-10-08 07:22:32 
2024-10-08 07:22:32 05:22:32.595 VPS ERROR VauException: Transcript Error: Exception thrown whilst trying to decrypt VAU message: Tag mismatch
2024-10-08 07:22:32 de.gematik.vau.lib.exceptions.VauDecryptionException: Exception thrown whilst trying to decrypt VAU message: Tag mismatch
2024-10-08 07:22:32     at de.gematik.vau.lib.AbstractVauStateMachine.decryptVauMessage(AbstractVauStateMachine.java:181)
2024-10-08 07:22:32     at de.gematik.vau.server.VauServerController.decryptAndForwardRequest(VauServerController.java:125)
2024-10-08 07:22:32     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
2024-10-08 07:22:32     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-10-08 07:22:32     at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:198)
2024-10-08 07:22:32     at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
2024-10-08 07:22:32     at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:297)
2024-10-08 07:22:32     at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:478)
2024-10-08 07:22:32     at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
2024-10-08 07:22:32     at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122)
2024-10-08 07:22:32     at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
2024-10-08 07:22:32     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
2024-10-08 07:22:32     at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
2024-10-08 07:22:32     at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2024-10-08 07:22:32     at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299)
2024-10-08 07:22:32     at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337)
2024-10-08 07:22:32     at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2097)
2024-10-08 07:22:32     at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145)
2024-10-08 07:22:32     at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2024-10-08 07:22:32     at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
2024-10-08 07:22:32     at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2024-10-08 07:22:32     at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:415)
2024-10-08 07:22:32     at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:445)
2024-10-08 07:22:32     at reactor.netty.http.server.HttpServerOperations.handleLastHttpContent(HttpServerOperations.java:862)
2024-10-08 07:22:32     at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:784)
2024-10-08 07:22:32     at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:115)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-10-08 07:22:32     at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:311)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-10-08 07:22:32     at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
2024-10-08 07:22:32     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
2024-10-08 07:22:32     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
2024-10-08 07:22:32     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-10-08 07:22:32     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2024-10-08 07:22:32     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-10-08 07:22:32     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
2024-10-08 07:22:32     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
2024-10-08 07:22:32     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
2024-10-08 07:22:32     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
2024-10-08 07:22:32     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
2024-10-08 07:22:32     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-10-08 07:22:32     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-10-08 07:22:32     at java.base/java.lang.Thread.run(Unknown Source)
2024-10-08 07:22:32 Caused by: javax.crypto.AEADBadTagException: Tag mismatch
2024-10-08 07:22:32     at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(Unknown Source)
2024-10-08 07:22:32     at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(Unknown Source)
2024-10-08 07:22:32     at java.base/javax.crypto.Cipher.doFinal(Unknown Source)
2024-10-08 07:22:32     at de.gematik.vau.lib.AbstractVauStateMachine.decryptWithAesGcm(AbstractVauStateMachine.java:150)
2024-10-08 07:22:32     at de.gematik.vau.lib.AbstractVauStateMachine.decryptVauMessage(AbstractVauStateMachine.java:175)
2024-10-08 07:22:32     ... 50 common frames omitted
2024-10-08 07:22:32 05:22:32.602 VPS ERROR ServerExceptionHandler: {ErrorCode=5, MessageType=Error, Message=Transcript Error: Exception thrown whilst trying to decrypt VAU message: Tag mismatch}
``` 
From my point of view the vau-server recieves the inner message, can detect the structural header information but anything is wron how the message was encrypted

**Comment by KillerCodeMonkey** [comment] 2024-10-08 10:21
same

**Comment by KillerCodeMonkey** [comment] 2024-10-08 11:22
@CEiderEVIDENT make sure are incrementing/setting the correct request counter. I forgot it and was sending another request with counter 0 which led to the mismatch error.

**Comment by KillerCodeMonkey** [comment] 2024-10-08 13:06
yes.

it is not necessary for the handshake requests, but if you want to get the nonce and so on in the next step you need to do it.

I just used the provided code here as a base to work on and created my own VauClient.
There i can set and pass the current request count.

My Vau-CLient is more or less stateless, so i pass all necessary information (vaucid, encryption, decryption keys, keyid, request counter) between software parts, because we are forced to mix programming languages -> using c# for all those encryption stuff and nodejs/electron for our main application.

**Comment by KillerCodeMonkey** [comment] 2024-10-08 13:10
@CEiderEVIDENT If you need more help or just some idea/information exchange you can contact me per mail bengt@codaline.io

But to be honest... i am far away from a dotnet/c# expert... and i never will/wanted to be it. :P

**Comment by CEiderEVIDENT** [comment] 2024-10-09 08:03
After making some changes to ste the request-counter to a value!=0, the message is being succesfully decrypted

```java
2024-10-09 09:57:21 07:57:21.857 VPS INFO VauServerController: Received request for VAU-CID: /1728460637227
2024-10-09 09:57:21 07:57:21.857 VPS TRACE EncryptedVauMessage: trying to decrypt:
2024-10-09 09:57:21       Complete message     : 0200010000000000000001e5bb9d5fc4932a24b7ea98db99981c6c0bccc3d7cb780bb3658de0cae941f25b493f20e200000000000000016d349873aa1067c84291e13ec82be9dda5555fa0a9e929fe472878654048b3972cf3dc2bbff4e235ceef36dc26f44309bddb9a4c7723ab9407f0f5ad481b3344dfe9c5a8d1b7df388468f53a70866f2f9b2b5d7c55b67f4c72786874a878e513b72b33116e
2024-10-09 09:57:21       Message size (Bytes) : 156
2024-10-09 09:57:21       Complete header      : 0200010000000000000001e5bb9d5fc4932a24b7ea98db99981c6c0bccc3d7cb780bb3658de0cae941f25b
2024-10-09 09:57:21       Key to decrypt (K2_c2s_app_data): 6e904dc0d4d91b7ebc7759cd7f7a447666e8fe20a78d6a48321902fbb6878f15
2024-10-09 09:57:21       -------------------------------
2024-10-09 09:57:21       Version  (1 Byte): 02
2024-10-09 09:57:21       PU       (1 Byte): 00
2024-10-09 09:57:21       Request  (1 Byte): 01
2024-10-09 09:57:21       Counter  (8 Byte): 0000000000000001
2024-10-09 09:57:21       KeyId   (32 Byte): e5bb9d5fc4932a24b7ea98db99981c6c0bccc3d7cb780bb3658de0cae941f25b
2024-10-09 09:57:21       IV      (12 Byte): 493f20e20000000000000001
2024-10-09 09:57:21       CT + GMAC        : 6d349873aa1067c84291e13ec82be9dda5555fa0a9e929fe472878654048b3972cf3dc2bbff4e235ceef36dc26f44309bddb9a4c7723ab9407f0f5ad481b3344dfe9c5a8d1b7df388468f53a70866f2f9b2b5d7c55b67f4c72786874a878e513b72b33116e
2024-10-09 09:57:21 
2024-10-09 09:57:21 07:57:21.858 VPS TRACE AbstractVauStateMachine: Successful decrypted ct as: 
2024-10-09 09:57:21  GET /VAU-Status HTTP/1.1
``` 
And the decrypted resutl looks the same as that what has been encrypted

**Comment by CEiderEVIDENT** [comment] 2024-10-09 08:33
> After making some changes to ste the request-counter to a value!=0, the message is being succesfully decrypted
Only works for first request with counter=1. On Counter =2 the same error as before occurs

**Comment by KillerCodeMonkey** [comment] 2024-10-09 10:44
@CEiderEVIDENT make sure you are sending maybe another request.
I am doing the handshake, after that getting the nonce with counter 1 and after that the VAU-Status with counter 2 and it is working.

**Comment by KillerCodeMonkey** [comment] 2024-10-10 07:16
@gematik1 i tried it again. And it is the case, that when the "epa-vau-proxy-server" receives a request counter >1 results in a tag mismatch.

e.g. first handshake, then get nonce with counter 1 (as bytes 00000001) and after that try to start authentication process or just get the vau-status with counter 2 (00000002) leads to a "tag mismatch error".

Just sending 1 all the time is a workaround for development.

But i guess this is then more an issue with the vau-proxy image?

i already triet latest image 1.0.11. Same problem there.

**Comment by MikeKurtze** [comment] 2024-10-14 07:23
We have found the Problem and we will provide an update. The Problem is that the library AesGcm changes the initialization vector in function initializeIV() before it's used for encryption.

**Comment by KillerCodeMonkey** [comment] 2024-10-14 13:51
@MikeKurtze i am not a crypto expert, but just for your information - if i remember it correctly an iv should not be reused especially when used with AesGCM.

So please make sure it will not introduce an attack opportunity or weakening the whole procedure.

**Comment by MikeKurtze** [comment] 2024-10-14 14:14
Yes, this it's correct and the AesGCM creates an IV via random value. The Bug here is, that our impementation extends/change the IV accordingly to spezification, but in the header value of the encrypted message is placed the random value, not the used IV. Thats the reason, the decryption fails.

**Comment by KillerCodeMonkey** [comment] 2024-10-14 17:56
ah okay. thanks for clarification :)

**Comment by KillerCodeMonkey** [comment] 2024-10-15 11:09
@MikeKurtze in the latest release only the EncryptMessage method was changed, but i guess the DecryptMessage needs to be changed as well.

**Comment by CEiderEVIDENT** [comment] 2024-10-18 08:42
Version 1.0.2 still has the error, fix does not work

**Comment by KillerCodeMonkey** [comment] 2024-10-18 08:43
@CEiderEVIDENT check the PR i created. Adapt the changes and it should work

**Comment by CEiderEVIDENT** [comment] 2024-10-18 09:08
@KillerCodeMonkey : Your fix in PR#1 fiexs the error succesfully. Great job

**Comment by MikeKurtze** [comment] 2024-10-22 11:17
@KillerCodeMonkey : thanks for your correction. This fix the bug with request counter. We are currrently changing the handling of the random value and will provide a correction soon. Thanks

**Comment by KillerCodeMonkey** [comment] 2024-10-30 08:30
@MikeKurtze after a week or so... can you maybe specify what "soon" means in your context :D?

**Comment by MikeKurtze** [comment] 2024-11-04 11:37
We have made an update to our C#- implementation. First of all we have removed all KSON references and conversions. THE CBOR format is simliar to JSON, but not identical. This would only cause confusion. Next we have made changes to the AES encryptionand decryption. The random value and the counter must be passed in as parameters, and the resulting IV is created from them. This can be retrieved using the GET method ans is also used for encryption and decryption. We have also added a test class named "EpaDeploymentTest" to test the handshake and the VAU status. We have tested this agaiunst our epa deployment environment.

**Comment by fnoGematik** [comment] 2024-11-07 09:26
Hey @CEiderEVIDENT & @KillerCodeMonkey,

We would be delighted if you could try out the new version (v1.0.4) and provide us with feedback. Otherwise we would close this ticket.

Best Regards,

**Comment by KillerCodeMonkey** [comment] 2024-11-07 09:48
@fnoGematik i already closed my PRs with the comment, that it is working for me with version >=1.0.3

**Comment by CEiderEVIDENT** [comment] 2024-11-07 10:15
Using code of version 1.0.4 works on PU-System an DC-Mocks

**Closed** 2024-11-08 09:02 UTC
